services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  database: null
